#!/bin/bash

. $HOME/backup.cfg


echo ======= $myname = `date` - S3 file pushing $datestr started >$mlog

s3cmd --no-progress --skip-existing --delete-removed sync /home/dok/backups/ s3://DOK-backups 1>>$mlog 2>>$mlog

echo `date` $myname - S3 file pushing $datestr finished >>$mlog

do_final;
