#!/bin/bash

. $HOME/backup.cfg

myname=`basename $0`
mlog=$log-$myname.log

echo `date` $myname - File backup $datestr started >$mlog

for i in "${bases[@]}" 
do
	nbase=$i
	nbase=`echo $nbase|sed 's/ /_/g'`
	nbase=`echo $nbase|sed 'y/абвгджзийклмнопрстуфхыэе/abvgdjzijklmnoprstufhyee/'|sed 's/[ьъ]//g; s/ё/yo/g; s/ц/ts/g; s/ч/ch/g; s/ш/sh/g; s/щ/sh/g; s/ю/yu/g; s/я/ya/'`;
	nbase=`echo $nbase|sed 'y/АБВГДЖЗИЙКЛМНОПРСТУФХЫЭЕ/ABVGDJZIJKLMNOPRSTUFHYEE/'|sed 's/[ЬЪ]//g; s/Ё/YO/g; s/Ц/TS/g; s/Ч/CH/g; s/Ш/SH/g; s/Щ/SH/g; s/Ю/YU/g; s/Я/YA/'`;
	fbase=$nbase-$datestr.tgz

# basedir -  полный путь к исходному каталогу всех баз
# i - название подкаталога базы
#
# bdir - полный путь каталога для бэкапов
# nbase - транслитерированное название базы. Название каталога для архивов, без пути
# fbase - файл архива базы, без пути.

	if [ ! -d $bdir/$nbase ]; then
		mkdir $bdir/$nbase
		echo Create $bdir/$nbase
	fi
	tar -czf $bdir/$nbase/$fbase -C$basedir "$i" 1>>/dev/null 2>>/dev/null
	if [ "$?" -eq 0 ]
	then
		echo $i backuped in to $bdir/$nbase/$fbase >>$mlog
	else
		echo $i not backuped. >>$mlog
	fi

done

echo `date` $myname - File backup $datestr finished >>$mlog

send_report $myname' at '$whost $mlog;
rm -f $mlog

