#!/bin/bash

. $HOME/backup.cfg

myname=`basename $0`
mlog=$log-$myname.log

echo `date` $myname - Trac environments backup $datestr started >$mlog

if [ ! -d $bdir ];
then
  mkdir $bdir;
  echo Create $bdir >>$mlog
fi

# bdir - полный путь каталога для бэкапов

for i in "${tracenv[@]}" 
do
	echo -- $i >>$mlog
	# проверим и удалим каталог ...backups/trac-<env>-<datestr>. Его создаcт trac-adm во время бэкапа
	tmpname=trac-$i-$datestr
	if [ -d $bdir/$tmpname ]; then
		rm -r $bdir/$tmpname
		echo Delete $bdir/$tmpname >>$mlog
	fi
	# проверим или создадим каталог ...backups/<env>. Он создается один раз. Туда будем класть затаренные <env>-$datestr.tgz
	if [ ! -d $bdir/$i ]; then
		mkdir $bdir/$i
		echo Create $bdir/$i >>$mlog
	fi
	
	$tracadm $tracdir/projects/$i hotcopy $bdir/$tmpname 1>>$mlog 2>>$mlog
	
	if [ "$?" -eq 0 ]
	then
		tar -czf $bdir/$i/$i-$datestr.tgz -C$bdir "$tmpname" 1>>/dev/null 2>>/dev/null
		echo -n $i backuped in to $bdir/$i/$i-$datestr.tgz with size: >>$mlog
		echo `du -hs $bdir/$i/$i-$datestr.tgz | cut -f1` >>$mlog
	else
		echo $i not backuped. >>$mlog
	fi

	if [ -d $bdir/$tmpname ]; then
		rm -r $bdir/$tmpname
		echo Delete $bdir/$tmpname >>$mlog
	fi

done

echo -- >>$mlog
echo `date` $myname - File backup $datestr finished >>$mlog

send_report $myname' at '$whost $mlog;
rm -f $mlog

